name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку, если она называется иначе
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Укажите версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask  # Установите необходимые зависимости

      - name: Build Docker image
        run: |
          docker build -t my-flask-app .

      - name: Run tests
        run: |
          # Здесь можно добавить команду для запуска тестов, если они есть
          echo "Running tests..."

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Убедитесь, что вы добавили это в секреты
          password: ${{ secrets.DOCKER_TOKEN }}      # Используем access token вместо пароля

      - name: Push Docker image
        run: |
          docker tag my-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
